### ISSUE TITLE
Multiple missing entry errors.

### ISSUE THREAD

**Issue by Ookami313** [Nukme/InspectEquip#1]
After updating to the current version, I'm getting the following errors. The covenant errors occur while logging in while the PVP errors occur shortly after logging in, I assume when the addon is trying to update a database or something. Thanks.

1x AceLocale-3.0-6: InspectEquip: Missing entry for 'Kyrian Nathrian Weapon Vendors'
[string "@InspectEquip\ItemSources.lua"]:12: in main chunk

1x AceLocale-3.0-6: InspectEquip: Missing entry for 'Venthyr Nathrian Weapon Vendors'
[string "@InspectEquip\ItemSources.lua"]:13: in main chunk

1x AceLocale-3.0-6: InspectEquip: Missing entry for 'Necrolord Nathrian Weapon Vendors'
[string "@InspectEquip\ItemSources.lua"]:14: in main chunk

1x AceLocale-3.0-6: InspectEquip: Missing entry for 'Night Fae Nathrian Weapon Vendors'
[string "@InspectEquip\ItemSources.lua"]:15: in main chunk

1x AceLocale-3.0-6: InspectEquip: Missing entry for 'Dread'
[string "@InspectEquip\Core.lua"]:813: in function `IsPvPItem'
[string "@InspectEquip\Core.lua"]:856: in function `GetItemData'
[string "@InspectEquip\Core.lua"]:873: in function `GetItemSourceCategories'
[string "@InspectEquip\Core.lua"]:604: in function `Inspect'
[string "@InspectEquip\Core.lua"]:437: in function <InspectEquip\Core.lua:434>
[string "=(tail call)"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `Show'
[string "@FrameXML\UIParent.lua"]:2997: in function `SetUIPanel'
[string "@FrameXML\UIParent.lua"]:2842: in function `ShowUIPanel'
[string "@FrameXML\UIParent.lua"]:2710: in function <FrameXML\UIParent.lua:2706>
[string "=[C]"]: in function `SetAttribute'
[string "@FrameXML\UIParent.lua"]:3562: in function <FrameXML\UIParent.lua:3541>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `ShowUIPanel'
[string "@FrameXML\CharacterFrame.lua"]:21: in function `ToggleCharacter'
[string "TOGGLECHARACTER0"]:1: in function <[string "TOGGLECHARACTER0"]:1>

1x AceLocale-3.0-6: InspectEquip: Missing entry for 'Sinister'
[string "@InspectEquip\Core.lua"]:814: in function `IsPvPItem'
[string "@InspectEquip\Core.lua"]:856: in function `GetItemData'
[string "@InspectEquip\Core.lua"]:873: in function `GetItemSourceCategories'
[string "@InspectEquip\Core.lua"]:604: in function `Inspect'
[string "@InspectEquip\Core.lua"]:437: in function <InspectEquip\Core.lua:434>
[string "=(tail call)"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `Show'
[string "@FrameXML\UIParent.lua"]:2997: in function `SetUIPanel'
[string "@FrameXML\UIParent.lua"]:2842: in function `ShowUIPanel'
[string "@FrameXML\UIParent.lua"]:2710: in function <FrameXML\UIParent.lua:2706>
[string "=[C]"]: in function `SetAttribute'
[string "@FrameXML\UIParent.lua"]:3562: in function <FrameXML\UIParent.lua:3541>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `ShowUIPanel'
[string "@FrameXML\CharacterFrame.lua"]:21: in function `ToggleCharacter'
[string "TOGGLECHARACTER0"]:1: in function <[string "TOGGLECHARACTER0"]:1>

1x AceLocale-3.0-6: InspectEquip: Missing entry for 'Notorious'
[string "@InspectEquip\Core.lua"]:815: in function `IsPvPItem'
[string "@InspectEquip\Core.lua"]:856: in function `GetItemData'
[string "@InspectEquip\Core.lua"]:873: in function `GetItemSourceCategories'
[string "@InspectEquip\Core.lua"]:604: in function `Inspect'
[string "@InspectEquip\Core.lua"]:437: in function <InspectEquip\Core.lua:434>
[string "=(tail call)"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `Show'
[string "@FrameXML\UIParent.lua"]:2997: in function `SetUIPanel'
[string "@FrameXML\UIParent.lua"]:2842: in function `ShowUIPanel'
[string "@FrameXML\UIParent.lua"]:2710: in function <FrameXML\UIParent.lua:2706>
[string "=[C]"]: in function `SetAttribute'
[string "@FrameXML\UIParent.lua"]:3562: in function <FrameXML\UIParent.lua:3541>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `ShowUIPanel'
[string "@FrameXML\CharacterFrame.lua"]:21: in function `ToggleCharacter'
[string "TOGGLECHARACTER0"]:1: in function <[string "TOGGLECHARACTER0"]:1>

1x AceLocale-3.0-6: InspectEquip: Missing entry for 'Corrupted'
[string "@InspectEquip\Core.lua"]:816: in function `IsPvPItem'
[string "@InspectEquip\Core.lua"]:856: in function `GetItemData'
[string "@InspectEquip\Core.lua"]:873: in function `GetItemSourceCategories'
[string "@InspectEquip\Core.lua"]:604: in function `Inspect'
[string "@InspectEquip\Core.lua"]:437: in function <InspectEquip\Core.lua:434>
[string "=(tail call)"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `Show'
[string "@FrameXML\UIParent.lua"]:2997: in function `SetUIPanel'
[string "@FrameXML\UIParent.lua"]:2842: in function `ShowUIPanel'
[string "@FrameXML\UIParent.lua"]:2710: in function <FrameXML\UIParent.lua:2706>
[string "=[C]"]: in function `SetAttribute'
[string "@FrameXML\UIParent.lua"]:3562: in function <FrameXML\UIParent.lua:3541>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `ShowUIPanel'
[string "@FrameXML\CharacterFrame.lua"]:21: in function `ToggleCharacter'
[string "TOGGLECHARACTER0"]:1: in function <[string "TOGGLECHARACTER0"]:1>

1x AceLocale-3.0-6: InspectEquip: Missing entry for 'Sinful'
[string "@InspectEquip\Core.lua"]:817: in function `IsPvPItem'
[string "@InspectEquip\Core.lua"]:856: in function `GetItemData'
[string "@InspectEquip\Core.lua"]:873: in function `GetItemSourceCategories'
[string "@InspectEquip\Core.lua"]:604: in function `Inspect'
[string "@InspectEquip\Core.lua"]:437: in function <InspectEquip\Core.lua:434>
[string "=(tail call)"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `Show'
[string "@FrameXML\UIParent.lua"]:2997: in function `SetUIPanel'
[string "@FrameXML\UIParent.lua"]:2842: in function `ShowUIPanel'
[string "@FrameXML\UIParent.lua"]:2710: in function <FrameXML\UIParent.lua:2706>
[string "=[C]"]: in function `SetAttribute'
[string "@FrameXML\UIParent.lua"]:3562: in function <FrameXML\UIParent.lua:3541>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `ShowUIPanel'
[string "@FrameXML\CharacterFrame.lua"]:21: in function `ToggleCharacter'
[string "TOGGLECHARACTER0"]:1: in function <[string "TOGGLECHARACTER0"]:1>

1x AceLocale-3.0-6: InspectEquip: Missing entry for 'Unchained'
[string "@InspectEquip\Core.lua"]:818: in function `IsPvPItem'
[string "@InspectEquip\Core.lua"]:856: in function `GetItemData'
[string "@InspectEquip\Core.lua"]:873: in function `GetItemSourceCategories'
[string "@InspectEquip\Core.lua"]:604: in function `Inspect'
[string "@InspectEquip\Core.lua"]:437: in function <InspectEquip\Core.lua:434>
[string "=(tail call)"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `Show'
[string "@FrameXML\UIParent.lua"]:2997: in function `SetUIPanel'
[string "@FrameXML\UIParent.lua"]:2842: in function `ShowUIPanel'
[string "@FrameXML\UIParent.lua"]:2710: in function <FrameXML\UIParent.lua:2706>
[string "=[C]"]: in function `SetAttribute'
[string "@FrameXML\UIParent.lua"]:3562: in function <FrameXML\UIParent.lua:3541>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `ShowUIPanel'
[string "@FrameXML\CharacterFrame.lua"]:21: in function `ToggleCharacter'
[string "TOGGLECHARACTER0"]:1: in function <[string "TOGGLECHARACTER0"]:1>

1x AceLocale-3.0-6: InspectEquip: Missing entry for 'Cosmic'
[string "@InspectEquip\Core.lua"]:820: in function `IsPvPItem'
[string "@InspectEquip\Core.lua"]:856: in function `GetItemData'
[string "@InspectEquip\Core.lua"]:873: in function `GetItemSourceCategories'
[string "@InspectEquip\Core.lua"]:604: in function `Inspect'
[string "@InspectEquip\Core.lua"]:437: in function <InspectEquip\Core.lua:434>
[string "=(tail call)"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `Show'
[string "@FrameXML\UIParent.lua"]:2997: in function `SetUIPanel'
[string "@FrameXML\UIParent.lua"]:2842: in function `ShowUIPanel'
[string "@FrameXML\UIParent.lua"]:2710: in function <FrameXML\UIParent.lua:2706>
[string "=[C]"]: in function `SetAttribute'
[string "@FrameXML\UIParent.lua"]:3562: in function <FrameXML\UIParent.lua:3541>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `ShowUIPanel'
[string "@FrameXML\CharacterFrame.lua"]:21: in function `ToggleCharacter'
[string "TOGGLECHARACTER0"]:1: in function <[string "TOGGLECHARACTER0"]:1>

1x AceLocale-3.0-6: InspectEquip: Missing entry for 'Aspirant'
[string "@InspectEquip\Core.lua"]:822: in function `IsPvPItem'
[string "@InspectEquip\Core.lua"]:856: in function `GetItemData'
[string "@InspectEquip\Core.lua"]:873: in function `GetItemSourceCategories'
[string "@InspectEquip\Core.lua"]:604: in function `Inspect'
[string "@InspectEquip\Core.lua"]:437: in function <InspectEquip\Core.lua:434>
[string "=(tail call)"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `Show'
[string "@FrameXML\UIParent.lua"]:2997: in function `SetUIPanel'
[string "@FrameXML\UIParent.lua"]:2842: in function `ShowUIPanel'
[string "@FrameXML\UIParent.lua"]:2710: in function <FrameXML\UIParent.lua:2706>
[string "=[C]"]: in function `SetAttribute'
[string "@FrameXML\UIParent.lua"]:3562: in function <FrameXML\UIParent.lua:3541>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `ShowUIPanel'
[string "@FrameXML\CharacterFrame.lua"]:21: in function `ToggleCharacter'
[string "TOGGLECHARACTER0"]:1: in function <[string "TOGGLECHARACTER0"]:1>

1x AceLocale-3.0-6: InspectEquip: Missing entry for 'Gladiator'
[string "@InspectEquip\Core.lua"]:824: in function `IsPvPItem'
[string "@InspectEquip\Core.lua"]:856: in function `GetItemData'
[string "@InspectEquip\Core.lua"]:873: in function `GetItemSourceCategories'
[string "@InspectEquip\Core.lua"]:604: in function `Inspect'
[string "@InspectEquip\Core.lua"]:437: in function <InspectEquip\Core.lua:434>
[string "=(tail call)"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `Show'
[string "@FrameXML\UIParent.lua"]:2997: in function `SetUIPanel'
[string "@FrameXML\UIParent.lua"]:2842: in function `ShowUIPanel'
[string "@FrameXML\UIParent.lua"]:2710: in function <FrameXML\UIParent.lua:2706>
[string "=[C]"]: in function `SetAttribute'
[string "@FrameXML\UIParent.lua"]:3562: in function <FrameXML\UIParent.lua:3541>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `ShowUIPanel'
[string "@FrameXML\CharacterFrame.lua"]:21: in function `ToggleCharacter'
[string "TOGGLECHARACTER0"]:1: in function <[string "TOGGLECHARACTER0"]:1>

1x AceLocale-3.0-6: InspectEquip: Missing entry for 'Legendary'
[string "@InspectEquip\Core.lua"]:609: in function `Inspect'
[string "@InspectEquip\Core.lua"]:437: in function <InspectEquip\Core.lua:434>
[string "=(tail call)"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `Show'
[string "@FrameXML\UIParent.lua"]:2997: in function `SetUIPanel'
[string "@FrameXML\UIParent.lua"]:2842: in function `ShowUIPanel'
[string "@FrameXML\UIParent.lua"]:2710: in function <FrameXML\UIParent.lua:2706>
[string "=[C]"]: in function `SetAttribute'
[string "@FrameXML\UIParent.lua"]:3562: in function <FrameXML\UIParent.lua:3541>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `ShowUIPanel'
[string "@FrameXML\CharacterFrame.lua"]:21: in function `ToggleCharacter'
[string "TOGGLECHARACTER0"]:1: in function <[string "TOGGLECHARACTER0"]:1>

**Comment by Nukme** [comment]
Fixed in the latest release. It should work now on English gameclient.
